### ISSUE TITLE
4.1.4.5838 Bug view.windowMinSize,view.windowMaxSize

### ISSUE THREAD

**Issue by lastSpectator** [c-smile/sciter-sdk#71] opened 2018-03-23 07:39 UTC
view.windowMinSize=(1000,703);
view.windowMaxSize=(1600,870);

**Comment by c-smile** [comment] 2018-03-23 17:05
And the problem is? On what OS?

**Comment by lastSpectator** [comment] 2018-03-24 00:37
view.windowMinSize=(1000,703);
view.windowMaxSize=(1600,870);

When the width of a window is dragged, the width is a fixed value, not a range value（1000-1600）.
The height is no problem。

**Comment by c-smile** [comment] 2018-03-24 00:57
Thanks, it is clear now.

Fixed by svn:5847

**Closed by c-smile** 2018-03-24 00:57 UTC
